package com.dx.demi.archdiary.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.dx.demi.archdiary.bean.Project;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PROJECT".
*/
public class ProjectDao extends AbstractDao<Project, Long> {

    public static final String TABLENAME = "PROJECT";

    /**
     * Properties of entity Project.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property ProjName = new Property(1, String.class, "projName", false, "projname");
        public final static Property ProjState = new Property(2, String.class, "projState", false, "projdtate");
        public final static Property ProjHost = new Property(3, String.class, "projHost", false, "projhost");
        public final static Property ProjDescrib = new Property(4, String.class, "projDescrib", false, "projdescrib");
    }


    public ProjectDao(DaoConfig config) {
        super(config);
    }
    
    public ProjectDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PROJECT\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL ," + // 0: id
                "\"projname\" TEXT UNIQUE ," + // 1: projName
                "\"projdtate\" TEXT," + // 2: projState
                "\"projhost\" TEXT," + // 3: projHost
                "\"projdescrib\" TEXT);"); // 4: projDescrib
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PROJECT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Project entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String projName = entity.getProjName();
        if (projName != null) {
            stmt.bindString(2, projName);
        }
 
        String projState = entity.getProjState();
        if (projState != null) {
            stmt.bindString(3, projState);
        }
 
        String projHost = entity.getProjHost();
        if (projHost != null) {
            stmt.bindString(4, projHost);
        }
 
        String projDescrib = entity.getProjDescrib();
        if (projDescrib != null) {
            stmt.bindString(5, projDescrib);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Project entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String projName = entity.getProjName();
        if (projName != null) {
            stmt.bindString(2, projName);
        }
 
        String projState = entity.getProjState();
        if (projState != null) {
            stmt.bindString(3, projState);
        }
 
        String projHost = entity.getProjHost();
        if (projHost != null) {
            stmt.bindString(4, projHost);
        }
 
        String projDescrib = entity.getProjDescrib();
        if (projDescrib != null) {
            stmt.bindString(5, projDescrib);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public Project readEntity(Cursor cursor, int offset) {
        Project entity = new Project( //
            cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // projName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // projState
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // projHost
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // projDescrib
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Project entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setProjName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setProjState(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setProjHost(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setProjDescrib(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Project entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Project entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Project entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
